version: '3'
services:
  #PHP Service
  vimily_php:
    image: vimily/laravel:latest-dev
    container_name: vimily_php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www:z
    networks:
      - vimily_network
    command: |
      -wait tcp://vimily_db:3306 -timeout 1m php-fpm
    user: '1000'

  #Nginx Service
  vimily_nginx:
    image: nginx:alpine
    container_name: vimily_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
      - "443:443"
    volumes:
      - ./:/var/www:z
      - ./:/etc/nginx/conf.d/:z
    networks:
      - vimily_network

  #MySQL Service
  vimily_db:
    image: mysql:5.7
    container_name: vimily_db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - vimily_network

#Docker Networks
networks:
  vimily_network:

volumes:
  dbdata:
    driver: local
